#!/bin/sh
TEMP=/tmp/answer$$

whiptail --title "Main Menu" --menu "Category: " 0 0 0 \
	u "Utils" \
	f "Firewall" \
	l "Logs" \
	s "System" \
	2>$TEMP
	mainchoice=`cat $TEMP`
	case $mainchoice in

                #### Firewall Menu ####

		f)

		{
		whiptail --title "Administrative tasks"  --menu  "Tasks :" 0 0 0 \
			1 "Display firewall settings" \
			2 "Restore firewall settings" \
			3 "Flush Firewall settings" \
			4 "Monitor SYSLOG firewall" \
			5 "Save Firewall Settings" \
			2>$TEMP
		choice=`cat $TEMP`
		case $choice in
		        1)      sudo iptables -L -n -v
        		        ;;
		        2)      sudo iptables-restore </etc/iptables/rules.v4
				sudo ip6tables-restore </etc/iptables/rules.v6
	        	        sudo iptables -L -n -v
	                	;;
	        	3)      sudo iptables --flush
		                sudo iptables -L -n -v
		                ;;
			4)	watch -n 10 "sudo tail -n 50 /var/log/syslog | grep \"iptables denied\" |  cut -d ' ' -f4,14,15,22,23 | grep -v '244.0.0'"
				;;
			5)	ipset save > /etc/ipset.up.rules
				iptables-save > /etc/iptables/rules.v4
				;;
		esac
		}
		;;

                #### Logs Menu ####

                l)

                {
                whiptail --title "Logs"  --menu  "Logs :" 0 0 0 \
                        1 "imap Logins" \
                        2 "" \
                        3 "" \
                        4 "" \
                        2>$TEMP
                choice=`cat $TEMP`
                case $choice in
                        1)	cat /var/log/syslog | grep imap | grep Login | cut -d ' ' -f1,2,3,4,8,9,11
                                ;;
                        2)
                                ;;
                        3)
                                ;;
                        4)
                                ;;
                esac
                }
                ;;


                #### System Menu ####

                s)

                {
                whiptail --title "System tasks"  --menu  "Tasks :" 0 0 0 \
                        1 "Update System" \
			2 "Reload Apache Server" \
                        2>$TEMP
                systemchoice=`cat $TEMP`
                case $systemchoice in
                        1) 	sudo apt-get update
				sudo apt-get dist-upgrade
                        ;;
			2) 	sudo service apache2 reload
				sudo systemctl daemon-reload
				sudo service apache2 status
			;;
                esac
                }
                ;;

		#### Utiltiy Menu ####

		u)

                {
                whiptail --title "Utility tasks"  --menu  "Tasks :" 0 0 0 \
                        1 "List Enabled Services" \
                        2 "List Diabled Services" \
			3 "Sync GDRIVE (root)" \
                        2>$TEMP
                utilitychoice=`cat $TEMP`
                case $utilitychoice in
                        1)	service --status-all | grep "\[ + \]"
				;;
                        2)      echo Note: A Services is considered disabled based on it\'s upstart script
                                           So id thre is no upstart script it\'s considered disabled
                                service --status-all | grep "\[ - \]"
                        	;;
			3)	gdrive sync upload /root/raspbacksync 0B2zgUBjeak0QNXl0YjFDTjRMS2c
				;;
                esac
                }
                ;;
	esac
rm `echo $TEMP`
